package com.xdev.communicator.models.enums;


import com.fasterxml.jackson.annotation.JsonValue;

public enum ExpenseCategory {
    FUEL,
    LUBRICANTS,
    VEHICLE_PARTS_SERVICE,
    HEAVY_EQUIPMENT_WORKS,
    ELECTRICAL_MATERIALS_WORKS,
    PLUMBING_MATERIALS,
    CONSTRUCTION_MATERIALS,
    CLEANING_SUPPLIES,
    PACKAGING_CONTAINERS,
    OFFICE_SUPPLIES_PRINTING,
    LAB_ANALYSIS_FEES,
    GOVERNMENT_TAXES_FEES,
    COURIER_POST_SHIPPING,
    TOOLS_HARDWARE_SERVICES,
    SAFETY_INSURANCE,
    MEALS_CATERING,
    MACHINE_MAINTENANCE_REPAIR,
    AGRICULTURE_SUPPLIES,
    TRANSPORT_LOGISTICS,
    DONATIONS_SOCIAL,
    UTILITIES_WATER,
    FACTORY_CONSUMABLES,
    TOLLS_AND_ROAD_FEES,
    NON_OPERATING_PERSONAL,
    OTHER;

    @JsonValue
    public String toJson() { return name(); }
}
