name: Deploy Parent to GitHub Maven

on:
  # Build every push to main that touches the parent or its workflow
  push:
    branches: [ main ]
    paths:
      - 'pom.xml'
      - 'xdev-base/**'
      - 'xdev-security/**'
      - '.github/workflows/maven-publish.yml'
  # Manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Needed to upload to GitHub Packages
    permissions:
      contents: read
      packages: write

    steps:
      # 1) Check out the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Install JDK 21 and enable Maven cache
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven
          # Inject GitHub Packages creds automatically
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      # 3) Create settings.xml with the same credentials (optional but explicit)
      - name: Create Maven settings.xml
        run: |
          mkdir -p ~/.m2
          cat > ~/.m2/settings.xml <<EOF
          <settings xmlns="http://maven.apache.org/SETTINGS/1.2.0">
            <servers>
              <server>
                <id>github</id>
                  <username>${{ github.actor }}</username>
                <password>${{ secrets.GITHUB_TOKEN }}</password>
              </server>
            </servers>
          </settings>
          EOF

      # 4) Build & deploy the parent POM
      - name: Build & deploy parent POM
        run: mvn -B -s ~/.m2/settings.xml --no-transfer-progress clean deploy -DskipTests
